name: Create database
description: Creates database on Postgres server


runs:
    using: composite
        
    steps:
      - name: Install psql
        shell: bash
        run: |
          apt-get update
          apt-get install --yes --no-install-recommends postgresql-client      
